<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PackageId>SolNeat.PolicyEngine.OpenIddict</PackageId>
		<Authors>SolNeat</Authors>
		<Description>A lightweight headless RBAC PAP/PDP/PEP authorization engine integrated seamlessly with OpenIddict.</Description>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\SolNeat.PolicyEngine\SolNeat.PolicyEngine.csproj" />
		<PackageReference Include="OpenIddict.Abstractions" Version="7.7.1" />
		<PackageReference Include="OpenIddict.Server" Version="7.7.1" />
	</ItemGroup>

</Project>